apiVersion: v1
kind: Pod
metadata:
  labels:
    run: valheim-server
  name: vailheim-server
  namespace: default
spec:
  containers:
    - image: phx.ocir.io/axmvl4uui9gb/oraclelinux/valheim-server:latest
      imagePullPolicy: Never
      name: valheim-server
      ports:
        - containerPort: 2456
          protocol: UDP
          name: valheim-udp-2456
        - containerPort: 2456
          protocol: TCP
          name: valheim-tcp-2456
      resources:
        requests:
          memory: "16G"
          cpu: "250m"
        limits:
          memory: "16G"
          cpu: "500m"
      securityContext:
        capabilities:
          add:
            - SYS_NICE
            - SYS_RESOURCE
            - NET_ADMIN
            - AUDIT_WRITE
  restartPolicy: Always
  nodeName: 0.0.0.0
